version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            sudo gem update --system
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
       - run:
          name: Run tests
          command: >
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci
            tests split --split-by=timings --timings-type=classname)

            echo $TESTFILES

            bundle exec rspec --profile 10 \
                              --format << parameters.results_format >> \
                              --out ~/test_reports/rspec.xml \
                              --format progress \
                              ${TESTFILES}
